[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "onemississipi-e407e"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
